import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Bell, CalendarDays, CircleDollarSign, LayoutDashboard, LogOut, Plus, ReceiptText, Settings, TrendingUp, WalletCards, Search, Trash2 } from 'lucide-react'
import { Session } from '@supabase/supabase-js'
import { Auth } from './components/Auth'
import { supabase } from './lib/supabase'
import { createTransaction, deleteTransaction, getBudgets, getCategories, getTransactions, saveBudget, Transaction, TransactionType, Budget } from './lib/finance'

const naira = new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 })
const fallbackCategories: Record<TransactionType, string[]> = {
  income: ['Salary', 'Tutoring', 'Gifts', 'Freelance', 'Other income'],
  expense: ['Food & groceries', 'Transport', 'Housing', 'Utilities', 'Health', 'Education', 'Entertainment', 'Shopping', 'Subscriptions', 'Other expense'],
  investment: ['Investments'],
}

type Page = 'dashboard' | 'transactions' | 'budgets' | 'insights' | 'settings'
function readableError(error: unknown, fallback: string) { if (error && typeof error === 'object') { const e = error as { message?: string; details?: string; hint?: string; code?: string }; const parts = [e.message, e.details, e.hint, e.code ? `Code: ${e.code}` : ''].filter(Boolean); if (parts.length) return parts.join(' — ') } return error instanceof Error ? error.message : fallback }

export default function App() {
  const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(true); const [page, setPage] = useState<Page>('dashboard')
  const [transactions, setTransactions] = useState<Transaction[]>([]); const [categories, setCategories] = useState<{ id: string; name: string }[]>([])
  const [showForm, setShowForm] = useState(false); const [type, setType] = useState<TransactionType>('expense'); const [amount, setAmount] = useState(''); const [description, setDescription] = useState(''); const [categoryId, setCategoryId] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const [search, setSearch] = useState(''); const [budgets, setBudgets] = useState<Budget[]>([]); const [budgetCategory, setBudgetCategory] = useState(''); const [budgetAmount, setBudgetAmount] = useState('')

  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => listener.subscription.unsubscribe() }, [])
  useEffect(() => { if (!session?.user.id) return; getTransactions(session.user.id).then(setTransactions).catch(e => setError(`Could not load transactions: ${readableError(e, 'Unknown error')}`)) }, [session?.user.id])
  useEffect(() => { if (!session?.user.id) return; getCategories('expense').then(c => setCategories(c.length ? c : fallbackCategories.expense.map(name => ({ id: '', name })))).catch(() => setCategories(fallbackCategories.expense.map(name => ({ id: '', name })))) }, [session?.user.id])
  useEffect(() => { if (!session?.user.id || page !== 'budgets') return; const month = new Date().toISOString().slice(0, 7) + '-01'; getBudgets(session.user.id, month).then(setBudgets).catch(e => setError(`Could not load budgets: ${readableError(e, 'Unknown error')}`)) }, [session?.user.id, page])
  useEffect(() => { if (!session?.user.id || !showForm) return; getCategories(type).then(c => setCategories(c.length ? c : fallbackCategories[type].map(name => ({ id: '', name })))).catch(() => setCategories(fallbackCategories[type].map(name => ({ id: '', name })))) }, [session?.user.id, type, showForm])

  const income = useMemo(() => transactions.filter(t => t.type === 'income').reduce((s, t) => s + Number(t.amount), 0), [transactions]); const expenses = useMemo(() => transactions.filter(t => t.type === 'expense').reduce((s, t) => s + Number(t.amount), 0), [transactions]); const investments = useMemo(() => transactions.filter(t => t.type === 'investment').reduce((s, t) => s + Number(t.amount), 0), [transactions])
  const filtered = useMemo(() => transactions.filter(t => `${t.description ?? ''} ${t.category?.name ?? ''}`.toLowerCase().includes(search.toLowerCase())), [transactions, search])

  async function add() { if (!session?.user.id) return; const value = Number(amount); if (!value || value <= 0) return setError('Enter an amount greater than 0.'); if (!description.trim()) return setError('Add a short description.'); setSaving(true); setError(''); try { const tx = await createTransaction({ user_id: session.user.id, type, amount: value, currency: 'NGN', transaction_date: date, description: description.trim(), category_id: categoryId || null }); setTransactions(current => [tx, ...current]); setAmount(''); setDescription(''); setCategoryId(''); setShowForm(false) } catch (e) { setError(`Could not save transaction: ${readableError(e, 'Unknown Supabase error')}`) } finally { setSaving(false) } }
  async function remove(id: string) { if (!session?.user.id || !confirm('Delete this transaction?')) return; try { await deleteTransaction(session.user.id, id); setTransactions(current => current.filter(t => t.id !== id)) } catch (e) { setError(`Could not delete transaction: ${readableError(e, 'Unknown error')}`) } }
  async function addBudget() { if (!session?.user.id || !budgetCategory || Number(budgetAmount) < 0) return; try { const month = new Date().toISOString().slice(0, 7) + '-01'; const b = await saveBudget({ user_id: session.user.id, category_id: budgetCategory, month, amount: Number(budgetAmount), currency: 'NGN' }); setBudgets(current => [...current.filter(x => x.category_id !== b.category_id), b]); setBudgetAmount('') } catch (e) { setError(`Could not save budget: ${readableError(e, 'Unknown error')}`) } }

  if (loading) return <main className="auth-page"><div className="auth-card"><div className="brand auth-brand"><div className="logo">F</div><span>FinRec</span></div><p className="muted">Loading your secure workspace…</p></div></main>; if (!session) return <Auth />
  const nav = [{ id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'transactions', label: 'Transactions', icon: ReceiptText }, { id: 'budgets', label: 'Budgets', icon: WalletCards }, { id: 'insights', label: 'Insights', icon: BarChart3 }, { id: 'settings', label: 'Settings', icon: Settings }] as const
  return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">F</div><span>FinRec</span></div><nav>{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={page === item.id ? 'active' : ''} onClick={() => { setPage(item.id); setError('') }}><Icon size={19}/>{item.label}</button> })}</nav><div className="side-note"><Bell size={17}/><div><strong>Monthly review</strong><p>Keep recording daily for better forecasts.</p></div></div><button className="logout" onClick={() => supabase.auth.signOut()}><LogOut size={17}/> Sign out</button></aside>
    <main className="main"><header><div><p className="eyebrow">PERSONAL FINANCE</p><h1>{nav.find(n => n.id === page)?.label}</h1><p className="muted">{page === 'dashboard' ? 'Your financial picture, based on your recorded transactions.' : page === 'transactions' ? 'Review and manage your income, expenses and investments.' : page === 'budgets' ? 'Set monthly limits and keep spending visible.' : page === 'insights' ? 'Understand patterns in your financial activity.' : 'Manage your FinRec workspace.'}</p></div><button className="primary" onClick={() => { setError(''); setShowForm(true) }}><Plus size={18}/> Add transaction</button></header>{error && !showForm && <div className="error-banner">{error}</div>}
      {page === 'dashboard' && <><section className="cards"><div className="card"><span>Income</span><strong>{naira.format(income)}</strong><small className="positive">Recorded</small></div><div className="card"><span>Expenses</span><strong>{naira.format(expenses)}</strong><small>{transactions.filter(t => t.type === 'expense').length} transactions</small></div><div className="card"><span>Investments</span><strong>{naira.format(investments)}</strong><small className="positive">Recorded separately</small></div><div className="card highlight"><span>Net cash flow</span><strong>{naira.format(income - expenses - investments)}</strong><small>{income - expenses - investments >= 0 ? 'After investments' : 'Current deficit'}</small></div></section><div className="grid"><section className="panel"><div className="panel-head"><div><h2>Recent transactions</h2><p>Your latest recorded activity</p></div></div><div className="transactions">{transactions.length === 0 ? <div className="empty"><ReceiptText size={22}/><p>No transactions yet.</p></div> : transactions.slice(0, 8).map(t => <div className="tx" key={t.id}><div className={`tx-icon ${t.type}`}><CircleDollarSign size={18}/></div><div className="tx-info"><strong>{t.description || 'Transaction'}</strong><span>{t.category?.name || (t.type === 'investment' ? 'Investments' : 'Uncategorised')} · {new Date(t.transaction_date + 'T00:00:00').toLocaleDateString('en-NG', { day: 'numeric', month: 'short' })}</span></div><strong className={t.type === 'income' ? 'income' : 'expense'}>{t.type === 'income' ? '+' : '−'}{naira.format(Number(t.amount))}</strong></div>)}</div></section><section className="panel insight"><div className="panel-head"><div><h2>Next month to watch</h2><p>Transparent signals based on your data</p></div></div><div className="signal"><div className="signal-dot"></div><div><strong>Build your history</strong><p>Daily entries will make month-to-month spending patterns more useful.</p></div></div><div className="forecast"><CalendarDays size={18}/><div><span>Forecast status</span><strong>{transactions.length >= 10 ? 'Early pattern available' : `${transactions.length}/10 transactions for early pattern`}</strong></div></div></section></div></>}
      {page === 'transactions' && <section className="panel"><div className="toolbar"><div className="search"><Search size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search transactions"/></div><span>{filtered.length} records</span></div><div className="transactions">{filtered.length === 0 ? <div className="empty"><ReceiptText size={22}/><p>No matching transactions.</p></div> : filtered.map(t => <div className="tx" key={t.id}><div className={`tx-icon ${t.type}`}><CircleDollarSign size={18}/></div><div className="tx-info"><strong>{t.description || 'Transaction'}</strong><span>{t.category?.name || (t.type === 'investment' ? 'Investments' : 'Uncategorised')} · {new Date(t.transaction_date + 'T00:00:00').toLocaleDateString('en-NG')}</span></div><strong className={t.type === 'income' ? 'income' : 'expense'}>{t.type === 'income' ? '+' : '−'}{naira.format(Number(t.amount))}</strong><button className="icon-button" onClick={() => remove(t.id)} aria-label="Delete transaction"><Trash2 size={16}/></button></div>)}</div></section>}
      {page === 'budgets' && <section className="panel"><div className="panel-head"><div><h2>This month's budgets</h2><p>Set a limit for an expense category.</p></div></div><div className="budget-form"><select value={budgetCategory} onChange={e => setBudgetCategory(e.target.value)}><option value="">Select expense category</option>{categories.filter(c => c.id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input inputMode="decimal" value={budgetAmount} onChange={e => setBudgetAmount(e.target.value)} placeholder="Monthly limit"/><button className="primary" onClick={addBudget}>Save budget</button></div><div className="transactions">{budgets.length === 0 ? <div className="empty"><WalletCards size={22}/><p>No budgets set yet.</p></div> : budgets.map(b => <div className="tx" key={b.id}><div className="tx-info"><strong>{b.category?.name || 'Category'}</strong><span>Monthly budget</span></div><strong>{naira.format(Number(b.amount))}</strong></div>)}</div></section>}
      {page === 'insights' && <section className="grid"><div className="panel"><h2>Financial snapshot</h2><div className="forecast"><TrendingUp size={18}/><div><span>Savings after investments</span><strong>{naira.format(income - expenses - investments)}</strong></div></div><div className="forecast"><BarChart3 size={18}/><div><span>Investment contributions</span><strong>{naira.format(investments)}</strong></div></div></div><div className="panel"><h2>Next month to watch</h2><div className="signal"><div className="signal-dot"></div><div><strong>Keep recording daily</strong><p>More history will allow stronger month-to-month comparisons and forecasts.</p></div></div></div></section>}
      {page === 'settings' && <section className="panel"><h2>Settings</h2><p className="muted" style={{marginTop:8}}>Your account</p><div className="forecast"><Settings size={18}/><div><span>Signed in as</span><strong>{session.user.email}</strong></div></div><div className="forecast"><span>Default currency</span><strong>NGN — Nigerian Naira</strong></div></section>}
    </main>
    {showForm && <div className="modal-backdrop" onClick={() => !saving && setShowForm(false)}><div className="modal" onClick={e => e.stopPropagation()}><div className="panel-head"><div><h2>Add transaction</h2><p>Record income, an expense, or an investment.</p></div><button className="close" onClick={() => !saving && setShowForm(false)}>×</button></div>{error && <div className="error-banner">{error}</div>}<div className="tabs"><button className={type === 'expense' ? 'selected' : ''} onClick={() => setType('expense')}>Expense</button><button className={type === 'income' ? 'selected' : ''} onClick={() => setType('income')}>Income</button><button className={type === 'investment' ? 'selected' : ''} onClick={() => setType('investment')}>Investment</button></div><label>Description<input value={description} onChange={e => setDescription(e.target.value)} placeholder="e.g. Salary, Tutoring or Groceries"/></label><label>Amount<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0"/></label><label>Date<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>Category<select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">No category / choose later</option>{categories.map((c, i) => <option key={`${c.id}-${c.name}-${i}`} value={c.id}>{c.name}</option>)}</select></label><button className="primary full" onClick={add} disabled={saving}>{saving ? 'Saving…' : 'Save transaction'}</button></div></div>}
  </div>
}
